/**
 * @namespace nz.co.siliconstreet.vdmdiagrammer.helpers
 * @fileoverview Safe XML/SVG Processing Utility.
 * @description Standardizes raw SVG strings generated by headless engines into 
 * universally compliant XML documents for file exports. Enforces CSS-based 
 * centering to ensure standalone diagrams render perfectly in any browser 
 * while retaining absolute dimensions for native zooming and panning.
 */
export default class SvgProcessor {
    
    /**
     * @public
     * @static
     * @description Parses, sanitizes, and standardizes a raw SVG string.
     * @param {string} sRawSvg - The raw SVG string from the rendering engine.
     * @returns {string} The standardized SVG XML string ready for file export.
     * @throws {Error} If the string cannot be parsed into a valid XML document.
     */
    public static standardize(sRawSvg: string): string {
        // 1. Pre-Sanitization: Convert HTML entities to prevent strict XML parser crashes.
        const sPreCleanedSvg = sRawSvg.replace(/&nbsp;/gi, "&#160;");

        const oParser = new DOMParser();
        const oDoc = oParser.parseFromString(sPreCleanedSvg, "image/svg+xml");

        const oParserError = oDoc.querySelector("parsererror");
        if (oParserError) {
            throw new Error(`SVG XML Document parsing failed: ${oParserError.textContent}`);
        }

        const oSvgNode = oDoc.documentElement as unknown as SVGSVGElement;

        // 2. Structural Cleanup: Remove XML comments and processing instructions
        this._removeNonElementNodes(oDoc);

        // 3. Namespace Injection: Ensures native recognition by browsers and vector software
        if (!oSvgNode.getAttribute("xmlns")) {
            oSvgNode.setAttribute("xmlns", "http://www.w3.org/2000/svg");
        }
        if (!oSvgNode.getAttribute("xmlns:xlink")) {
            oSvgNode.setAttribute("xmlns:xlink", "http://www.w3.org/1999/xlink");
        }

        // 4. BEST PRACTICE ALIGNMENT & ZOOM FIX
        // We MUST retain the original intrinsic width/height attributes (e.g., width="490pt").
        // Overriding these with 100% destroys the browser's ability to generate scrollbars,
        // resulting in the "zooming into whitespace" bug.

        // Remove PlantUML's catastrophic distortion lock
        if (oSvgNode.getAttribute("preserveAspectRatio") === "none") {
            oSvgNode.removeAttribute("preserveAspectRatio");
        }

        // Use CSS to center the standalone file horizontally in the browser.
        // This centers the diagram WITHOUT destroying the physical dimensions needed for natural panning/zooming.
        let sInlineStyle = oSvgNode.getAttribute("style") || "";
        
        // Clean out conflicting display or margin rules if they exist
        sInlineStyle = sInlineStyle.replace(/margin\s*:[^;]+;?/gi, "")
                                   .replace(/display\s*:[^;]+;?/gi, "");
        
        // Append the centering rules
        sInlineStyle += " display: block; margin: 0 auto;";
        oSvgNode.setAttribute("style", sInlineStyle.trim());

        // 5. Security Sanitization
        const aScripts = oSvgNode.querySelectorAll("script");
        aScripts.forEach((oScript) => {
            if (oScript.parentNode) {
                oScript.parentNode.removeChild(oScript);
            }
        });

        // 6. Serialize and return
        const oSerializer = new XMLSerializer();
        return oSerializer.serializeToString(oDoc);
    }

    /**
     * @private
     * @static
     * @description Recursively traverses an XML DOM tree and safely removes 
     * Comments and Processing Instructions.
     * @param {Node} oNode - The current XML DOM Node.
     * @returns {void}
     */
    private static _removeNonElementNodes(oNode: Node): void {
        let i = oNode.childNodes.length;
        
        while (i--) {
            const oChild = oNode.childNodes[i];
            
            // Node.COMMENT_NODE === 8, Node.PROCESSING_INSTRUCTION_NODE === 7
            if (oChild.nodeType === 8 || oChild.nodeType === 7) {
                oNode.removeChild(oChild);
            } else if (oChild.nodeType === 1) { // Node.ELEMENT_NODE
                this._removeNonElementNodes(oChild);
            }
        }
    }
}